//temporary image
import temp from "images/temp.jpeg";

export const testPeopleData = [
  {
    id: 1,
    name: "the child elvis",
    age: 50,
    hair: "black",
    height: "4'1",
    eyes: "blue",
    location: {
      line1: "454 W 22nd St",
      line2: "",
      city: "NY",
      state: "NY",
      zipcode: "10011",
    },
    position: [51.505, -0.09],
    status: "missing",
    details:
      "small green dude went missing. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: temp,
  },
  {
    id: 2,
    name: "the child yoda",
    age: 50,
    hair: "black",
    height: "4'1",
    eyes: "blue",
    location: {
      line1: "39 W 37th St",
      line2: "",
      city: "NY",
      state: "NY",
      zipcode: "10018",
    },
    position: [51.515224, -0.114156],
    status: "missing",
    details:
      "small green dude went missing Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: temp,
  },
  {
    id: 3,
    name: "the child bean",
    age: 50,
    hair: "black",
    height: "4'1",
    eyes: "blue",
    location: {
      line1: "10 W 138th",
      line2: "",
      city: "NY",
      state: "NY",
      zipcode: "10037",
    },
    position: [51.517763, -0.134717],
    status: "found",
    details:
      "small green dude went missing Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: temp,
  },
  {
    id: 4,
    name: "the child",
    age: 50,
    hair: "black",
    height: "4'1",
    eyes: "blue",
    location: {
      line1: "222 E 93rd St",
      line2: "",
      city: "NY",
      state: "NY",
      zipcode: "10128",
    },
    position: [51.512478, -0.206471],
    status: "missing",
    details:
      "small green dude went missing Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: temp,
  },
  {
    id: 5,
    name: "the child",
    age: 50,
    hair: "black",
    height: "4'1",
    eyes: "blue",
    location: {
      line1: "200 Park Ave",
      line2: "",
      city: "NY",
      state: "NY",
      zipcode: "10166",
    },
    position: [51.485872, -0.094548],
    status: "found",
    details:
      "small green dude went missing Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: temp,
  },
];
